app = "fabs-ai-bi"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  # HTTP on port 80
  [[services.ports]]
    handlers = ["http"]
    port = 80

  # HTTPS on port 443
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
